/**
 * formatter.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Formats a ScoringResult and PrData into a polished GitHub Markdown comment.
 * ─────────────────────────────────────────────────────────────────────────────
 */

'use strict';

import { buildDataMarker, Delta } from './delta.js';
import { PrData, FileDetail, LlmAnalysis } from './scoring-rules.js';
import { ScoringResult, TriggeredRule } from './scorer.js';

// Max number of risky files to surface inline in the comment
const MAX_RISKY_FILES_SHOWN = 8;
// Max number of "passed" checks to list in the summary
const MAX_PASSED_SHOWN = 5;

/**
 * Formats a LlmAnalysis and PrData into a polished AI-first GitHub Markdown comment.
 */
export function formatLlmInsights(analysis: LlmAnalysis | null): string {
  if (!analysis) return '> ⚠️ _No AI Qualitative Review available for this diff._';

  return [
    '## 🤖 AI Qualitative Review',
    '',
    '> _Deep technical audit performed by Paranoid Senior Auditor (Local LLM)._',
    '',
    '### 🚨 Critical Security Audit',
    analysis.security,
    '',
    '### 🧱 Architecture & Logic Flaws',
    analysis.logic,
    '',
    '### 📉 Performance & Technical Debt',
    analysis.optimization,
    '',
    '### 🧹 Clean Code & Maintainability Violations',
    analysis.deadCode,
    '',
    '### 📝 Executive Summary',
    analysis.summary,
    '',
  ].join('\n');
}

/**
 * Builds the full Markdown PR comment from AI insights and raw PR data.
 */
export function formatComment(
  _result: any, 
  prData: PrData, 
  _delta: any,
  llmAnalysis: LlmAnalysis | null = null
): string {
  // ── Header ────────────────────────────────────────────────────────────────
  const header = [
    '# 🚦 AI Senior Auditor Analysis',
    '',
    '> **Line-by-line verification** and **logical sabotage detection** powered by local LLM.',
    '',
    '---',
  ].join('\n');

  // ── AI Insights ───────────────────────────────────────────────────────────
  const aiSection = formatLlmInsights(llmAnalysis);

  // ── PR Context Summary ────────────────────────────────────────────────────
  const contextSummary = [
    '### 📂 PR Context',
    '',
    `| Metric | Value |`,
    `|--------|-------|`,
    `| 📁 Files | ${prData.fileCount} |`,
    `| 📝 Lines | +${prData.totalAdditions} / -${prData.totalDeletions} (${prData.totalChanges} total) |`,
    '',
  ].join('\n');

  // ── Risky Files Table (Based on File Classification) ─────────────────────
  const riskyFiles = prData.fileDetails
    .filter((f: FileDetail) => f.isCritical || f.isConfig)
    .sort((a: any, b: any) => b.changes - a.changes)
    .slice(0, MAX_RISKY_FILES_SHOWN);

  let riskyFilesSection = '';
  if (riskyFiles.length > 0) {
    const rows = riskyFiles.map((f: FileDetail) => {
      const tags = [];
      if (f.isCritical) tags.push('`critical`');
      if (f.isConfig) tags.push('`config`');
      const changeStr = `+${f.additions} / -${f.deletions}`;
      return `| \`${f.path}\` | ${changeStr} | ${tags.join(' ')} |`;
    });

    riskyFilesSection = [
      '### ⚙️ High-Impact Components Modified',
      '',
      '| File | Changes | Tags |',
      '|------|---------|------|',
      ...rows,
      '',
    ].join('\n');
  }

  // ── Footer ────────────────────────────────────────────────────────────────
  const footer = [
    '---',
    '',
    '<sub>🤖 Generated by <strong>PR AI Auditor</strong> · ',
    'Local AI Review (Phi-3) · ',
    `Analysis run: ${new Date().toUTCString()}</sub>`,
    '',
  ].join('');

  return [
    header,
    aiSection,
    '---',
    contextSummary,
    riskyFilesSection,
    footer,
  ].join('\n');
}
